"""Demo document generator - creates hardcoded sample files."""

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pptx import Presentation
from pptx.util import Inches as PptxInches
from pathlib import Path


def create_demo_word_document():
    """Create a hardcoded demo Word document."""
    output_dir = Path("generated_documents")
    output_dir.mkdir(exist_ok=True)
    
    doc = Document()
    
    # Title
    title = doc.add_heading('Sample Business Report', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata
    doc.add_paragraph('Generated by AI Document Platform')
    doc.add_paragraph('Date: 2024-11-30')
    doc.add_paragraph('')
    
    # Executive Summary
    doc.add_heading('Executive Summary', level=1)
    doc.add_paragraph(
        'This is a sample business report generated by the AI Document Platform. '
        'The platform leverages advanced AI technology to create professional documents '
        'quickly and efficiently.'
    )
    doc.add_paragraph('')
    
    # Key Findings
    doc.add_heading('Key Findings', level=1)
    doc.add_paragraph('Our analysis has revealed the following key insights:', style='List Bullet')
    doc.add_paragraph('Revenue growth exceeded expectations by 25%', style='List Bullet')
    doc.add_paragraph('Customer satisfaction scores improved significantly', style='List Bullet')
    doc.add_paragraph('Market expansion into new regions shows promise', style='List Bullet')
    doc.add_paragraph('')
    
    # Recommendations
    doc.add_heading('Recommendations', level=1)
    doc.add_paragraph(
        'Based on our findings, we recommend the following actions:'
    )
    doc.add_paragraph('1. Increase investment in high-performing product lines')
    doc.add_paragraph('2. Expand customer support team to maintain satisfaction levels')
    doc.add_paragraph('3. Continue market research in emerging regions')
    doc.add_paragraph('')
    
    # Conclusion
    doc.add_heading('Conclusion', level=1)
    doc.add_paragraph(
        'The AI Document Platform demonstrates the power of combining artificial intelligence '
        'with document generation. This technology enables businesses to create professional '
        'documents in seconds, saving time and improving productivity.'
    )
    
    filepath = output_dir / "demo_document.docx"
    doc.save(str(filepath))
    print(f"Created demo Word document: {filepath}")
    return str(filepath)


def create_demo_powerpoint():
    """Create a hardcoded demo PowerPoint presentation."""
    output_dir = Path("generated_documents")
    output_dir.mkdir(exist_ok=True)
    
    prs = Presentation()
    
    # Title Slide
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = "AI Document Platform"
    title_slide.placeholders[1].text = "Professional Document Generation\nPowered by Google Gemini"
    
    # Slide 2: Overview
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Platform Overview"
    text_frame = slide.placeholders[1].text_frame
    text_frame.text = "Key Features:"
    
    p = text_frame.add_paragraph()
    p.text = "AI-powered content generation"
    p.level = 1
    
    p = text_frame.add_paragraph()
    p.text = "Support for Word and PowerPoint formats"
    p.level = 1
    
    p = text_frame.add_paragraph()
    p.text = "Simple, user-friendly interface"
    p.level = 1
    
    p = text_frame.add_paragraph()
    p.text = "Fast document creation"
    p.level = 1
    
    # Slide 3: Benefits
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Benefits"
    text_frame = slide.placeholders[1].text_frame
    text_frame.text = "Why use AI Document Platform?"
    
    p = text_frame.add_paragraph()
    p.text = "Save time on document creation"
    p.level = 1
    
    p = text_frame.add_paragraph()
    p.text = "Maintain professional quality"
    p.level = 1
    
    p = text_frame.add_paragraph()
    p.text = "Focus on content, not formatting"
    p.level = 1
    
    # Slide 4: Conclusion
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Get Started Today"
    text_frame = slide.placeholders[1].text_frame
    text_frame.text = "Experience the future of document creation with AI Document Platform"
    
    filepath = output_dir / "demo_presentation.pptx"
    prs.save(str(filepath))
    print(f"Created demo PowerPoint: {filepath}")
    return str(filepath)


if __name__ == "__main__":
    create_demo_word_document()
    create_demo_powerpoint()
    print("Demo files created successfully!")
